version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_NAME: pill-bug
    command: npm run dev
    ports:
      - "3000:3000"

  worker:
    image: node:latest
    working_dir: /app
    volumes:
      - ./worker:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_NAME: pill-bug
    command: npm run worker